apiVersion: v1
kind: Service
metadata:
  name: k8s-sample-app-mysql
  labels:
    app: k8s-sample-app
spec:
  ports:
    - port: 3306
  selector:
    app: k8s-sample-app
    tier: mysql
  clusterIP: None
