apiVersion: v1
kind: PersistentVolume
metadata:
  name: mysql-pv
  labels:
    app: k8s-sample-app
spec:
  accessModes:
  - ReadWriteOnce
  capacity:
    storage: 10Gi
  hostPath:
    path: /data/pods/mysql/datadir
