apiVersion: v1
kind: Service
metadata:
  name: mercadotech-mysql
  labels:
    app: mercadotech
spec:
  ports:
    - port: 3306
  selector:
    app: mercadotech
    tier: mysql
  clusterIP: None
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: mysql-pv-claim
  labels:
    app: mercadotech
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 20Gi
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: mercadotech-mysql
  labels:
    app: mercadotech
spec:
  selector:
    matchLabels:
      app: mercadotech
      tier: mysql
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: mercadotech
        tier: mysql
    spec:
      containers:
      - image: mysql:5.6
        name: mysql
        env:
        - name: MYSQL_ROOT_PASSWORD
          value: Root@123
        ports:
        - containerPort: 3306
          name: mysql
        volumeMounts:
        - name: mysql-persistent-storage
          mountPath: /var/lib/mysql
      volumes:
      - name: mysql-persistent-storage
        persistentVolumeClaim:
          claimName: mysql-pv-claim
